### ISSUE TITLE
关于目录内容的修正

### ISSUE THREAD

**Issue by Tolia-GH** [ITMO-Computer-Science-Group/ICSG-Wiki#1]
![image](https://user-images.githubusercontent.com/45510494/111058607-b16e7b00-84ca-11eb-9a59-427a93ed8183.png)需要加入俄语语法的链接

**Comment by Tolia-GH** [comment]
还需要加入历史的链接

**Comment by Ran-ying** [comment]
俄语语法已添加，在目录中删掉了历史，目前历史内容太少。
