### ISSUE TITLE
关于链接内容

### ISSUE THREAD

**Issue by Tolia-GH** [ITMO-Computer-Science-Group/ICSG-Wiki#2]

**Comment by Ran-ying** [comment]
内容不详细。

**Comment by Tolia-GH** [comment]
![image](https://user-images.githubusercontent.com/45510494/111072402-6fb6f200-8515-11eb-9ca3-50176879cbaf.png)
最好加入一个国内能用的讨论群组

**Comment by Tolia-GH** [comment]
错误报告我觉得可以直接题issue
